/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cvgenerator1;

import com.itextpdf.text.BaseColor;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.*;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPRow;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.IOException;

/**
 *
 * @author Dell
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jTextArea1.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CV Generator");
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 171, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Work Experience");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 280, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Company Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 103, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 171, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Work Done:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, -1));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 171, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Education Background");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 300, -1));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("College/University:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 103, -1));

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 171, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Title of Qualification A:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 135, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contact:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 193, 80, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 171, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 171, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Title of Qualification B:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 135, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, 80, -1));

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 171, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 171, -1));

        jLabel22.setText("About Me:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 151, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Set Skills:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 24));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 720, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 134, -1));

        jLabel9.setText("Profession Field:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 313, 110, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 171, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nationality:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 253, 80, -1));

        jButton1.setMnemonic('s');
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(39, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(39, 22));
        jButton1.setPreferredSize(new java.awt.Dimension(39, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 100, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PERSONAL INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 103, 80, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 171, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 133, 80, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 171, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 163, 80, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 171, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 171, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Date of Birth:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 283, 80, -1));

        jButton3.setText("Save");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 80, -1));

        jButton5.setText("Generate");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, -1));

        jLabel4.setText("Search by id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, -1, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 134, -1));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 134, -1));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 134, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Fname = jTextField1.getText();
        String Lname = jTextField2.getText();
        String Address = jTextField3.getText();
        String Contact = jTextField4.getText();
        String Email = jTextField5.getText();
        String Nationality = jTextField8.getText();
        String Dob = jTextField9.getText();
        String Prof_Field = jTextField7.getText();
        String Skill1 = jTextField14.getText();
        String Skill2 = jTextField6.getText();
        String Skill3 = jTextField18.getText();
        String Skill4 = jTextField11.getText();
        String Cname = jTextField12.getText();
        String Wdone = jTextField13.getText();
        String College = jTextField15.getText();
        String TOQA = jTextField16.getText();
        String TOQB = jTextField17.getText();
        String About = jTextArea1.getText();

        // Perform required field validation
        if (Fname.isEmpty() || Lname.isEmpty() || Address.isEmpty() || Contact.isEmpty() || Email.isEmpty() || Nationality.isEmpty() || Dob.isEmpty() || Prof_Field.isEmpty() || Skill1.isEmpty() || Cname.isEmpty() || Wdone.isEmpty() || College.isEmpty() || TOQA.isEmpty() || TOQB.isEmpty() || About.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!!!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String dburl = "jdbc:mysql://localhost/cvgenerator";
                String username = "root";
                String password = "";
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("this is connection");
                Connection cn = DriverManager.getConnection(dburl, username, password);

                String sql = "insert into user(Fname,Lname,Address,Contact,Email,Nationality,Dob,Prof_Field,Skill1,Skill2,Skill3,Skill4,Cname,Wdone,College,TOQA,TOQB,About) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                System.out.println(sql);
                PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                ps.setString(1, jTextField1.getText());
                ps.setString(2, jTextField2.getText());
                ps.setString(3, jTextField3.getText());
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText());
                ps.setString(6, jTextField8.getText());
                ps.setString(7, jTextField9.getText());
                ps.setString(8, jTextField7.getText());
                ps.setString(9, jTextField14.getText());
                ps.setString(10, jTextField6.getText());
                ps.setString(11, jTextField18.getText());
                ps.setString(12, jTextField11.getText());
                ps.setString(13, jTextField12.getText());
                ps.setString(14, jTextField13.getText());
                ps.setString(15, jTextField15.getText());
                ps.setString(16, jTextField16.getText());
                ps.setString(17, jTextField17.getText());
                ps.setString(18, jTextArea1.getText());

                int rowsAffected = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "saved successfully");

                if (rowsAffected > 0) {
                    ResultSet generatedKeys = ps.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        int insertedId = generatedKeys.getInt(1); // Assuming the ID is an integer
                        JOptionPane.showMessageDialog(this, "Your id is: " + insertedId);
                    }
                    generatedKeys.close();
                } else {
                    System.out.println("No rows were inserted.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Fname = jTextField1.getText();
        String Lname = jTextField2.getText();
        String Address = jTextField3.getText();
        String Contact = jTextField4.getText();
        String Email = jTextField5.getText();
        String Nationality = jTextField8.getText();
        String Dob = jTextField9.getText();
        String Prof_Field = jTextField7.getText();
        String Skill1 = jTextField14.getText();
        String Skill2 = jTextField6.getText();
        String Skill3 = jTextField18.getText();
        String Skill4 = jTextField11.getText();
        String Cname = jTextField12.getText();
        String Wdone = jTextField13.getText();
        String College = jTextField15.getText();
        String TOQA = jTextField16.getText();
        String TOQB = jTextField17.getText();
        String About = jTextArea1.getText();

        // Perform required field validation
        if (Fname.isEmpty() || Lname.isEmpty() || Address.isEmpty() || Contact.isEmpty() || Email.isEmpty() || Nationality.isEmpty() || Dob.isEmpty() || Prof_Field.isEmpty() || Skill1.isEmpty()  || Cname.isEmpty() || Wdone.isEmpty() || College.isEmpty() || TOQA.isEmpty() || TOQB.isEmpty() || About.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!!!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else {

            JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File(jTextField1.getText() + " " + jTextField2.getText() + "-CV" + ".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult == JFileChooser.APPROVE_OPTION) {
                String filePath = dialog.getSelectedFile().getPath();
                try {
                    Document myDocument = new Document();
                    PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));

                    myDocument.open();

                    PdfPTable table = new PdfPTable(2);
                    // table.getDefaultCell().setBorder(0);
//          myDocument.add(image);
                    myDocument.add(new Paragraph(jTextField1.getText() + "  " + jTextField2.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 36, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 9, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 9, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    myDocument.add(new Paragraph("CONTACT DETAILS", FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(" ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.PLAIN, BaseColor.DARK_GRAY)));

                    myDocument.add(new Paragraph("   "+jTextField5.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField4.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField3.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField8.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField9.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField7.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));

                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    myDocument.add(new Paragraph("SKILLS", FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(" ", FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    table.setHeaderRows(1);
                    table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
                   
                    table.addCell(jTextField14.getText());
                    table.addCell(jTextField6.getText());
                    table.addCell(jTextField18.getText());
                    table.addCell(jTextField11.getText());

                    myDocument.add(table);

                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    myDocument.add(new Paragraph("QUALIFICATIONS", FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(" ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.PLAIN, BaseColor.DARK_GRAY)));

                    myDocument.add(new Paragraph("   "+jTextField15.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField16.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("   "+jTextField17.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    myDocument.add(new Paragraph("WORK EXPERIENCE", FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(" ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.PLAIN, BaseColor.DARK_GRAY)));

                    myDocument.add(new Paragraph("   "+jTextField12.getText() + System.lineSeparator() + "   "+jTextField13.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));
//          myDocument.add(new Paragraph(txt_company2.getText()+System.lineSeparator()+txt_worktwo.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY)));
//          myDocument.add(new Paragraph(txt_company3.getText()+System.lineSeparator()+txt_workthree.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,7,Font.PLAIN,BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

                    myDocument.add(new Paragraph("About me", FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(" ", FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.PLAIN, BaseColor.DARK_GRAY)));

                    myDocument.add(new Paragraph(jTextArea1.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 11, Font.PLAIN, BaseColor.DARK_GRAY)));

//          myDocument.add(new Paragraph("REFERENCES",FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.BOLD,BaseColor.DARK_GRAY  )));
//          myDocument.add(new Paragraph("Available upon request",FontFactory.getFont(FontFactory.TIMES_BOLD,6,Font.PLAIN,BaseColor.DARK_GRAY  )));
                    myDocument.close();
                } catch (DocumentException | IOException e) {
                    e.printStackTrace();
                }
            }

    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(jTextField10.getText());

        try {
            String jdbcUrl = "jdbc:mysql://localhost/cvgenerator";
            String username = "root";
            String password = "";

            Connection conn = DriverManager.getConnection(jdbcUrl, username, password);

            int targetId = Integer.parseInt(jTextField10.getText()); // Replace with the ID you want to retrieve

            String query = "SELECT * FROM user WHERE id = ?";
            PreparedStatement pps = conn.prepareStatement(query);
            pps.setInt(1, targetId);

            ResultSet resultSet = pps.executeQuery();

            if (resultSet.next()) {
                // Retrieve data from all columns in the result set
//                int id = resultSet.getInt("id");
                String Fname = resultSet.getString("Fname");
                String Lname = resultSet.getString("Lname");
                String Address = resultSet.getString("Address");
                String Contact = resultSet.getString("Contact");
                String Email = resultSet.getString("Email");
                String Nationality = resultSet.getString("Nationality");
                String Dob = resultSet.getString("Dob");
                String Prof_Field = resultSet.getString("Prof_Field");
                String Skill1 = resultSet.getString("Skill1");
                String Skill2 = resultSet.getString("Skill2");
                String Skill3 = resultSet.getString("Skill3");
                String Skill4 = resultSet.getString("Skill4");
                String Cname = resultSet.getString("Cname");
                String Wdone = resultSet.getString("Wdone");
                String College = resultSet.getString("College");
                String TOQA = resultSet.getString("TOQA");
                String TOQB = resultSet.getString("TOQB");
                String About = resultSet.getString("About");

                jTextField1.setText(Fname);
                jTextField2.setText(Lname);
                jTextField3.setText(Address);
                jTextField4.setText(Contact);
                jTextField5.setText(Email);
                jTextField8.setText(Nationality);
                jTextField9.setText(Dob);
                jTextField7.setText(Prof_Field);
                jTextField14.setText(Skill1);
                jTextField6.setText(Skill2);
                jTextField18.setText(Skill3);
                jTextField11.setText(Skill4);
                jTextField12.setText(Cname);
                jTextField13.setText(Wdone);
                jTextField15.setText(College);
                jTextField16.setText(TOQA);
                jTextField17.setText(TOQB);
                jTextArea1.setText(About);

            } else {
                JOptionPane.showMessageDialog(this, "No data found for ID: " + targetId);

            }

            resultSet.close();
            pps.close();
            conn.close();
        } catch (SQLException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
